Add instructions
tannershimanek/cs4230-software-testing pull request #29
Opened 2023-10-19 04:01 UTC by natalinamateaki

2023-10-19 18:38 UTC, tannershimanek requested changes
Looks great! The only suggestion that I have is maybe change line 11 to say "Python 3" instead of "Python." This program will not work with anything below python3.

2023-10-20 20:17 UTC, walter-smith approved these changes
Looks good.

2023-10-20 22:14 UTC, tannershimanek reviewed
Looks good to me!

2023-10-20 22:14 UTC, tannershimanek approved these changes

2023-10-20 22:25 UTC, merged